### ISSUE TITLE
defaultSettings of the Module are not applied to some of module's projects

### ISSUE THREAD

**Issue by antonkulaga** [InTheNow/sbt-scalajs#17]
Banana-rdf fails in Intellij and Eclipse because lazy val rdf_common_jvm = rdfM.project(Jvm,Shared) does not apply default settings from rdfM (Module project), that include scalaVersion := 2.11.6

Seems like the problem occurs only for .project(Js,Shared) and .project(Jvm,Shared)

**Comment by InTheNow** [comment]
This is not a bug, but a required feature when the mode is set to `SbtLinkedBuild`as the setting, and code, in the shared project are added to the main project - eg rdf_jvm

**Comment by antonkulaga** [comment]
I may be wrong with exact formulation, but it looks like a reason why IDEA and Eclipse failed to import the build (projects did not get default build settings ScalaVersion := 2.11.6 and were automaticly interpreted by IDEA and Eclipse as 2.10.x projects)
