### ISSUE TITLE
Problems interacting with sbt-release and multiple scala versions

### ISSUE THREAD

**Issue by non** [InTheNow/sbt-scalajs#19]
I have updated [machinist](https://github.com/typelevel/machinist) with the goal of producing a new js-compatible release. I changed the organization to *org.spire-math* temporarily since I was having trouble publishing to *org.typelevel*. And I copied a setup that had worked very well recently for publishing 2.10 and 2.11 releases to Sonatype in one go.

It doesn't seem to work here (after being used with 4+ projects successfully) and the only thing that is different is the use of `sbt-scalajs`. I'm not sure what the problem is, but here is what I am seeing:

 1. Start to publish, things seem fine
 2. Submits JVM and JS jars for Scala 2.11 only.
 3. I have to cancel the release.

What I expect to happen is:

 1. Start to publish
 2. Submits JVM and JS jars for 2.10 and 2.11.
 3. Things are great.

I am using `crossScalaVersions` as well as `releaseCrossBuild := true`. I have tried using `release cross` explicitly, although my other projects don't need that due to the aforementioned settings.

Here's the complete [build.sbt](https://github.com/typelevel/machinist/blob/master/build.sbt) and [plugins.sbt](https://github.com/typelevel/machinist/blob/master/project/plugins.sbt). I'm using SBT 0.13.8.

Any ideas? I can approach the author of `sbt-release` as well but I thought you might have a better idea of what is happening.

**Comment by InTheNow** [comment]
@non Sorry for late-ish response, kids summer holidays, etc. So what follows is quick-ish:

This plugin is not actually used by cats (and most other scala.js projects). Rather the official sbt-scalajs is used from `org.scala.js`  eg: https://github.com/typelevel/machinist/blob/master/project/plugins.sbt#L4

Also, the issue of removing `src/main/scala_2.11` source directories just requires a different "trick" than in a normal build. 

For now, my best guess for machinest is `ReleaseStep(action = Command.process("publishSigned", _)) ` -> ``publishArtifacts`  as you have already [setup sbt-release for pgp](https://github.com/sbt/sbt-release#publishing-signed-releases).

All said and done - congrats for investing the time into the merky world of build and release management :)

**Comment by non** [comment]
Thanks! I'll give it a shot and report back.

**Comment by non** [comment]
It works! Thanks!
