### ISSUE TITLE
add a flag to get rid of _js and _jvm

### ISSUE THREAD

**Issue by antonkulaga** [InTheNow/sbt-scalajs#8]
Projects like plantain_js_sjs0.5_2.11 look ugly due to js-related suffixes in the name. 
In the same time it is convenient to have _js and _jvm suffixies in project ids. 
When name sbt property is not specified it is the same as project id, so you have to specify name := project_name_without_suffix for each _jvm and _js project manually. I think it is better to make plugin do this job. 
So, what I want is to let plugin delete _js and _jvm suffixies in project names, so we will get 
 plantain_sjs0.5_2.11 and  plantain_2.11 instead of  plantain_js_sjs0.5_2.11 and  plantain_jvm_2.11 respectively. It will also be nice if we will be able to turn on/off this suffix renaming.

**Comment by InTheNow** [comment]
Done
