### ISSUE TITLE
make it IDEA-14 friendly

### ISSUE THREAD

**Issue by antonkulaga** [InTheNow/sbt-scalajs#9]
I am trying to port accord library to scalajs ( https://github.com/antonkulaga/accord/tree/scalajs_support ), there I use sbt-scalajs plugin. It works well for IDEA
![borkenidea14](https://cloud.githubusercontent.com/assets/842436/5056002/f7b8388a-6c76-11e4-9957-728328b7f677.png)
-13, but it is totally broken for IDEA-14 (see screenshot). In IDEA-13 when something went wrong I used gen-idea, but for IDEA-14 I can only open the project from IDEA, as gen-idea does not support IDEA-14 yet (it generates files in older format)

**Comment by InTheNow** [comment]
issue covered by #4

**Comment by codingismy11to7** [comment]
Just saw this issue from somewhere else - you do know that IDEA (at least 14) with the Scala plugin (there used to be an SBT plugin but that's no longer needed) can natively open `.sbt` projects without using gen-idea, right? Even works fine with scala/scala.js cross projects...

**Comment by InTheNow** [comment]
@codingismy11to7 Thanks for pointing this out, I guess I should have closed this issue a while back.
